name = 'tutel'

[[tasks]]
desc = 'reset indices'
completed = false
index = 10

[[tasks]]
desc = 'todo.txt compat?'
completed = false
index = 14

[[tasks]]
desc = 'bring back tnav'
completed = false
index = 15

[[tasks]]
desc = 'sub categories through sub dirs'
completed = false
index = 16

[[tasks]]
desc = 'due dates'
completed = false
index = 19

[[tasks]]
desc = 'edit completion is borked'
completed = true
index = 20

[[tasks]]
desc = 'auto migration'
completed = false
index = 21

[[tasks]]
desc = 'tests proper'
completed = false
index = 22
