[package]
name = "tutel"
version = "0.2.0"
edition = "2018"
description = "a minimalist todo app"
authors = ["arthur"]
homepage = "https://www.github.com/InvalidName662/tutel"
repository = "https://www.github.com/InvalidName662/tutel"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.45"
clap = "2.33.3"
toml = "0.5.8"
ansi_term = "0.12.1"
serde = { version = "1.0.130", features = [ "derive" ] }
directories = "4.0.1"
libc = "0.2.112"
