[package]
name = "tutel"
version = "0.2.4"
edition = "2018"
description = "a minimalist todo app for terminal enthusiasts"
authors = ["arthur"]
homepage = "https://www.github.com/InvalidName662/tutel"
repository = "https://www.github.com/InvalidName662/tutel"
license = "MIT"

[dependencies]
anyhow = "1.0.45"
clap = "3.2.15"
toml = "0.5.8"
ansi_term = "0.12.1"
serde = "1.0.130"
tempfile = "3.3.0"

[build-dependencies]
clap = "3.2.15"
clap_complete = "3.2.3"
