complete -c tutel -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c tutel -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
complete -c tutel -n "__fish_use_subcommand" -f -a "new" -d 'create a new project'
complete -c tutel -n "__fish_use_subcommand" -f -a "add" -d 'add a new task'
complete -c tutel -n "__fish_use_subcommand" -f -a "done" -d 'mark a task as being completed'
complete -c tutel -n "__fish_use_subcommand" -f -a "rm" -d 'remove a task'
complete -c tutel -n "__fish_use_subcommand" -f -a "edit" -d 'edit an existing task'
complete -c tutel -n "__fish_use_subcommand" -f -a "completions" -d 'print shell completions'
complete -c tutel -n "__fish_seen_subcommand_from new" -s f -l force -d 'force project creation'
complete -c tutel -n "__fish_seen_subcommand_from new" -s h -l help -d 'Prints help information'
complete -c tutel -n "__fish_seen_subcommand_from add" -s c -l completed -d 'mark the task as already completed'
complete -c tutel -n "__fish_seen_subcommand_from add" -s h -l help -d 'Prints help information'
complete -c tutel -n "__fish_seen_subcommand_from done" -s ! -l not -d 'mark the task as not being done'
complete -c tutel -n "__fish_seen_subcommand_from done" -s a -l all -d 'select all tasks'
complete -c tutel -n "__fish_seen_subcommand_from done" -s h -l help -d 'Prints help information'
complete -c tutel -n "__fish_seen_subcommand_from rm" -s a -l all -d 'remove all tasks'
complete -c tutel -n "__fish_seen_subcommand_from rm" -s c -l cleanup -d 'remove all completed tasks'
complete -c tutel -n "__fish_seen_subcommand_from rm" -l project -d 'remove the whole project file'
complete -c tutel -n "__fish_seen_subcommand_from rm" -s h -l help -d 'Prints help information'
complete -c tutel -n "__fish_seen_subcommand_from edit" -s e -l editor -d 'the editor to use' -r
complete -c tutel -n "__fish_seen_subcommand_from edit" -s h -l help -d 'Prints help information'
complete -c tutel -n "__fish_seen_subcommand_from completions" -s h -l help -d 'Prints help information'
